# Generated by Django 3.1.10 on 2023-04-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='prodb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=100)),
                ('BookName', models.CharField(max_length=100)),
                ('AutherName', models.CharField(max_length=100)),
                ('Language', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('Image', models.ImageField(upload_to='')),
            ],
        ),
    ]
