# Generated by Django 3.1.10 on 2023-05-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='req',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('BookName', models.CharField(max_length=100)),
                ('AutherName', models.CharField(max_length=100)),
                ('Language', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('qty', models.IntegerField()),
            ],
        ),
    ]
