# Generated by Django 3.1.10 on 2023-05-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0002_req'),
    ]

    operations = [
        migrations.CreateModel(
            name='accept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100, null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('BookName', models.CharField(max_length=100)),
                ('AutherName', models.CharField(max_length=100)),
                ('Language', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('qty', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='req',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='req',
            name='Username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
