# Generated by Django 3.1.10 on 2023-05-04 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0003_auto_20230504_1448'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='accept',
            new_name='acceptdb',
        ),
    ]
