# Generated by Django 3.1.10 on 2023-05-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0006_cancel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='req',
            name='Language',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
