# Generated by Django 3.1.10 on 2023-05-28 03:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0007_auto_20230515_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptdb',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
