# Generated by Django 3.1.10 on 2023-05-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0008_acceptdb_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptdb',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
