# Generated by Django 3.1.10 on 2023-05-28 03:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0009_acceptdb_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptdb',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='acceptdb',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
