# Generated by Django 3.1.10 on 2023-05-28 03:55

import dataapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0011_auto_20230528_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptdb',
            name='start_date',
            field=models.DateField(default=dataapp.models.get_default_start_date),
        ),
    ]
