# Generated by Django 3.1.10 on 2023-05-28 04:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0012_auto_20230528_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptdb',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
