# Generated by Django 3.1.10 on 2023-05-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0013_auto_20230528_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptdb',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='acceptdb',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='acceptdb',
            name='Price',
            field=models.IntegerField(null=True),
        ),
    ]
