# Generated by Django 3.1.10 on 2023-05-28 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0014_auto_20230528_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptdb',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='acceptdb',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
