# Generated by Django 3.1.10 on 2023-05-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0015_auto_20230528_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnbook',
            name='end_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='returnbook',
            name='start_date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
