# Generated by Django 3.1.10 on 2023-05-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0016_auto_20230528_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnbook',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='returnbook',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
