# Generated by Django 3.1.10 on 2023-06-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0017_auto_20230528_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnbook',
            name='end_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='returnbook',
            name='start_date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
