# Generated by Django 3.1.10 on 2023-06-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0018_auto_20230607_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookName', models.CharField(max_length=100)),
                ('AutherName', models.CharField(max_length=100)),
                ('Due', models.IntegerField()),
                ('BookPrice', models.IntegerField()),
                ('TotalPrice', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='returnbook',
            name='Due',
            field=models.IntegerField(null=True),
        ),
    ]
