# Generated by Django 3.1.10 on 2023-06-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0019_auto_20230607_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='DuePrice',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='BookPrice',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Due',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='TotalPrice',
            field=models.IntegerField(null=True),
        ),
    ]
