# Generated by Django 3.1.10 on 2023-06-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0022_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='Username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
