# Generated by Django 3.1.10 on 2023-06-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0023_payments_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='complect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100, null=True)),
                ('BookName', models.CharField(max_length=100)),
                ('Due', models.CharField(max_length=100)),
                ('BookPrice', models.IntegerField(null=True)),
                ('DuePrice', models.CharField(max_length=100, null=True)),
                ('TotalPrice', models.IntegerField(null=True)),
            ],
        ),
    ]
