# Generated by Django 3.1.10 on 2023-04-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindb',
            name='Address',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='logindb',
            name='Mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='logindb',
            name='Phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='logindb',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
