# Generated by Django 3.1.10 on 2023-04-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0003_auto_20230427_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logindb',
            name='Address',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='logindb',
            name='Mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='logindb',
            name='Phone',
            field=models.IntegerField(null=True),
        ),
    ]
